org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.workers.max=8
org.gradle.caching=true
org.gradle.configuration-cache=false

mod_id=examplemod
mod_name=Example Mod
mod_description=This is an example mod!
mod_authors=NPG418
mod_license=MIT
mod_version=1.0-SNAPSHOT
mod_group_id=com.npg418.example