[versions]
minecraft-range = ">=1.21 <=1.21.1"

# https://fabricmc.net/develop
fabric-loader = "0.19.3"
fabric-loader-range = ">=0.19.3"
fabric-api = "0.116.15+1.21.1"
fabric-api-range = "*"

# https://maven.fabricmc.net/net/fabricmc/fabric-language-kotlin
fabric-kotlin = "1.13.13+kotlin.2.4.10"
fabric-kotlin-range = ">=1.13.13"

# https://modrinth.com/mod/modmenu/versions?l=fabric
modmenu = "11.0.4"

[libraries]
fabric-loader = { group = "net.fabricmc", name = "fabric-loader", version.ref = "fabric-loader" }
fabric-api = { group = "net.fabricmc.fabric-api", name = "fabric-api", version.ref = "fabric-api" }
fabric-kotlin = { group = "net.fabricmc", name = "fabric-language-kotlin", version.ref = "fabric-kotlin" }

modmenu = { group = "com.terraformersmc", name = "modmenu", version.ref = "modmenu" }